### ISSUE TITLE
Question about rebalance_batch function

### ISSUE THREAD

**Issue by recolic** [desert0616/gpma_bfs_demo#8]
Hi, I was trying to understand your code, and got confused by this function [`rebalance_batch`](https://github.com/desert0616/gpma_bfs_demo/blob/a605807bc5d9cb712df382102bfc136d24cae572/gpma.cuh#L574) . It looks like:

```c++
if (update_width <= 1024)
    ImplementationA(); // block_rebalancing_kernel
else
    ImplementationB(); // rebalancing_kernel
```

I thought `block_rebalancing_kernel` and `rebalancing_kernel` was just implementing the same feature, and they should be exchange-able. (maybe `block_rebalancing_kernel` is faster than `rebalancing_kernel` if `update_width <= 1024`).

So I changed the code to:

```c++
//if (update_width <= 1024)
//    ImplementationA(); // block_rebalancing_kernel
//else
    ImplementationB(); // rebalancing_kernel
```

but it's not working anymore... I'm not sure what's the relationship between `block_rebalancing_kernel` and `rebalancing_kernel`, and there's no documentation... Could you explain it for me?

Thanks a lot for your help!

**Comment by desert0616** [comment]
Hi, I tried to comment out lines 555-576 as well as line 581 of gpma.cuh.
It works on my side but becomes very slow as expected.
Can you provide more details about your issue (what does it mean "not working anymore")?
Thanks.

**Comment by recolic** [comment]
You're correct... I was just making some mistakes in my code...
